/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;
import java.sql.*;
import java.sql.DriverManager;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.ParseException;
    import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.JTextField;
import java.text.*;
import java.awt.print.*;
import java.util.Calendar;
/**
 *
 * @author Vishal_kumar
 */
public class create extends javax.swing.JFrame {

    //private static void setDefaultCloseOPeration(int EXIT_ON_CLOSE) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}
Connection con=null;
 ResultSet rs1=null;
    PreparedStatement pstmt=null,pstmt1=null;
    int flag;

    /**
     * Creates new form create
     */
    public create() {
        initComponents();
        try{
            con=DriverManager.getConnection("jdbc:ucanaccess://.\\shield.accdb");
        }catch(Exception e){
            System.out.println("problem in connection"+e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        secans = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        conpass = new javax.swing.JPasswordField();
        email = new javax.swing.JTextField();
        mob = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtsq = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtdob = new com.toedter.calendar.JDateChooser();
        cpass1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        secans.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        secans.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                secansKeyPressed(evt);
            }
        });
        jPanel1.add(secans);
        secans.setBounds(650, 470, 240, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("Create Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(470, 520, 140, 30);

        uname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(uname);
        uname.setBounds(650, 210, 240, 30);

        conpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        conpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                conpassKeyPressed(evt);
            }
        });
        jPanel1.add(conpass);
        conpass.setBounds(650, 570, 240, 30);

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(email);
        email.setBounds(650, 310, 240, 30);

        mob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(mob);
        mob.setBounds(650, 260, 240, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("User Name");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(470, 210, 140, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setText("Mobile Number");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(470, 260, 140, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 0));
        jLabel11.setText("Email id");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(470, 310, 140, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 0));
        jLabel12.setText("DOB");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(470, 360, 140, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 0));
        jLabel13.setText("Security Question");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(470, 410, 140, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 0, 0));
        jLabel14.setText("Security Answer");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(470, 460, 140, 30);

        txtsq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Your Pet name", "Your school name", "Your best friend name", "Place you want to go for trip" }));
        jPanel1.add(txtsq);
        txtsq.setBounds(650, 420, 240, 24);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("Conform Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(470, 570, 140, 30);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 0));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(750, 650, 90, 29);

        txtdob.setDateFormatString("dd-MMM-yyyy");
        jPanel1.add(txtdob);
        txtdob.setBounds(650, 360, 240, 30);

        cpass1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cpass1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cpass1KeyPressed(evt);
            }
        });
        jPanel1.add(cpass1);
        cpass1.setBounds(650, 520, 240, 30);

        jLabel1.setBackground(new java.awt.Color(153, 153, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/logoe.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 30, 480, 120);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Create Account");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(660, 140, 200, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1903, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void secansKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secansKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_secansKeyPressed

    private void conpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_conpassKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_conpassKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            
            System.out.println("done1");
            pstmt=con.prepareStatement("insert into login(username,password,mobile,emailid,dob,securitypara,securitycode,num,serialno)values(?,?,?,?,?,?,?,?,?)");
          pstmt1=con.prepareStatement("update login set serialno = 0 where num=0");
            String u=uname.getText();
             String c=conpass.getText();
               String e=email.getText();
                String s=secans.getText();
               String m=mob.getText();
               String cp=conpass.getText();
               int i=1;
               System.out.println("done2");
               pstmt.setString(1,u);
               pstmt.setString(5,((JTextField)txtdob.getDateEditor().getUiComponent()).getText());
               String r=txtsq.getSelectedItem().toString();
        System.out.println("done3");
              
               pstmt.setString(2,c);
               pstmt.setString(3,m);
                pstmt.setString(4,e);
               pstmt.setString(7,s);
               pstmt.setString(6,r);
               pstmt.setInt(8,i);
               System.out.println("done4");
               pstmt.setInt(9,i);
               System.out.println("done5");
               if(!u.equals(null)&& !c.equals(null) && !e.equals(null) & !s.equals(null) && !m.equals(null) && !cp.equals(null))
               {
                   System.out.println("donek");
             if(c.equals(cp))
             {
                
                 System.out.println("done6");
               pstmt.executeUpdate();
               pstmt1.executeUpdate();
               JOptionPane.showMessageDialog(null,"Profile is uploaded","Data Insertion",JOptionPane.PLAIN_MESSAGE);
               Login ob=new Login();
        ob.setVisible(true);
        this.setVisible(false);
             } 
               
               
              else
             {
                 JOptionPane.showMessageDialog(null,"Please check data you have inserted","Insertion  alert",JOptionPane.ERROR_MESSAGE);
             }
               }else
               {
                   JOptionPane.showMessageDialog(null,"Please check data you have inserted","Insertion  alert",JOptionPane.ERROR_MESSAGE);
               }
                   
                    
               
        }
         catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Please check batch number"+ex,"Insertion  alert",JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cpass1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpass1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpass1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new create().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField conpass;
    private javax.swing.JPasswordField cpass1;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mob;
    private javax.swing.JPasswordField secans;
    private com.toedter.calendar.JDateChooser txtdob;
    private javax.swing.JComboBox<String> txtsq;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
