/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

import java.sql.*;
import java.sql.DriverManager;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.ParseException;
    import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.JTextField;
import java.text.*;
import java.awt.print.*;

/**
 *
 * @author Vishal_kumar
 */
public class forgotpass extends javax.swing.JFrame {
     Connection con=null;
 ResultSet rs1=null;
    PreparedStatement pstmt=null;
    int flag;

    /**
     * Creates new form forgotpass
     */
    public forgotpass() {
        initComponents();
        try{
            con=DriverManager.getConnection("jdbc:ucanaccess://.\\shield.accdb");
        }catch(Exception e){
            System.out.println("problem in connection"+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        secans = new javax.swing.JPasswordField();
        txtsq = new javax.swing.JComboBox<>();
        mob = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setText("Mobile Number");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(500, 270, 140, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 0));
        jLabel11.setText("Email id");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(500, 220, 150, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 0));
        jLabel13.setText("Security Question");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(500, 320, 140, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 0, 0));
        jLabel14.setText("Security Answer");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(500, 370, 140, 30);

        secans.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        secans.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                secansKeyPressed(evt);
            }
        });
        jPanel1.add(secans);
        secans.setBounds(680, 370, 240, 30);

        txtsq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Your Pet name", "Your school name", "Your best friend name", "Place you want to go for trip" }));
        jPanel1.add(txtsq);
        txtsq.setBounds(680, 320, 240, 30);

        mob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(mob);
        mob.setBounds(680, 270, 240, 30);

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(email);
        email.setBounds(680, 220, 240, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 0));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(830, 430, 90, 29);

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(153, 0, 0));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(110, 400, 68, 29);

        jLabel1.setBackground(new java.awt.Color(153, 153, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/logoe.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 30, 480, 120);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Forgot Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(640, 140, 220, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1868, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void secansKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secansKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_secansKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{  
          
            Statement stmt=con.createStatement();
              String e=email.getText();
            String m=mob.getText();
            String s=secans.getText();
            String r=txtsq.getSelectedItem().toString();
            System.out.println("done1");
       ResultSet rs1=stmt.executeQuery("select * from login where num=1");
       System.out.println("done2");
       if(rs1.next())
       {
           System.out.println("done3");
          String u1=rs1.getString(1);
          String u2=rs1.getString(2);
          String u3=rs1.getString(3);
          String u4=rs1.getString(4);
          String u5=rs1.getString(5);
          String u6=rs1.getString(6);
          String u7=rs1.getString(7);
          String u8=rs1.getString(8);
          String u9=rs1.getString(9);
          System.out.println(e);
          System.out.println(u2);
          System.out.println(u3);
          System.out.println(u4);
          System.out.println(r);
          System.out.println(s);
          System.out.println(m);
          System.out.println(u8);
          System.out.println(u9);
          
          
          
          if (u2.equals(e) && u3.equals(r) && u4.equals(s) && u9.equals(m))
          {
              Forgotpass1 ob=new Forgotpass1();
        ob.setVisible(true);
        this.setVisible(false); 
          } else 
               JOptionPane.showMessageDialog(null,"Invalid Data Entered ");
       }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Login  ob= new Login();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mob;
    private javax.swing.JPasswordField secans;
    private javax.swing.JComboBox<String> txtsq;
    // End of variables declaration//GEN-END:variables
}
